language: python
python:
- '3.6'
- '3.7'
install:
- pip install -r requirements.txt
- pip install -r requirements_dev.txt
script:
- python setup.py install
- pytest test --cov
after_success:
- codecov
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  distributions: "sdist bdist_wheel"
  on:
    branch: master
    tags: true
    python: "3.6"
