language: python
python:
  - '3.6'
  - '3.7'
install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
script:
  - cd test && pytest --cov && cd ..
  - python setup.py install
after_success:
  - codecov
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  distributions: sdist bdist_wheel --universal
  on:
    branch: master
    tags: true
    python: "3.6"
